use_frameworks!

platform :ios, '10.0'

target 'LJTencentOpenAPI-iOS_Example' do
  pod 'LJTencentOpenAPI-iOS', :path => '../'

  target 'LJTencentOpenAPI-iOS_Tests' do
    inherit! :search_paths

    
  end
end
